##
## EPITECH PROJECT, 2026
## Makefile
## File description:
## Root Makefile
##

all:
	make -C lib/my/

clean:
	make clean -C lib/my/

fclean:
	make fclean -C lib/my/

re:	fclean all

.PHONY: all clean fclean re
